import type { Metadata } from "next";
import { Geist } from "next/font/google";

import Navbar from "~/components/navbar";
import { Toaster } from "~/components/ui/sonner";
import Providers from "~/providers";
import { TRPCReactProvider } from "~/trpc/react";

import "~/styles/globals.css";
import { auth } from "~/server/utils";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const authData = await auth();

	console.log({ authData });

	return (
		<html lang="en" className={`${geist.variable}`}>
			<body className="font-jetbrainsMono">
				<TRPCReactProvider>
					<Providers>
						<Navbar nickname={authData?.nickname} />
						{children}
						<Toaster />
					</Providers>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
